##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## my make file
##

NAME	=	

SRCS	=	

OBJS	=	

CC		=

RM		=

NCURSES_LIB = ./ncurses/

MYLIB = -L $(NCURSES_LIB) -l$(NCURSES_LIB) \

all: 
		@ make -s -C $(NCURSES_LIB)

clean:
		@ make clean -s -C $(NCURSES_LIB)

fclean:	
		@ make fclean -s -C $(NCURSES_LIB)

re: 
		@ make re -s -C $(NCURSES_LIB)

.PHONY: all clean fclean re