##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## my make file
##

NAME	=	

SRCS	=	

OBJS	=	

CC		=

RM		=

NCURSES_LIB = ./ncurses/
SFML_LIB = ./sfml/

all: 
		@ make -s -C $(NCURSES_LIB)
		@ make -s -C $(SFML_LIB)

clean:
		@ make clean -s -C $(NCURSES_LIB)
		@ make clean -s -C $(SFML_LIB)

fclean:	
		@ make fclean -s -C $(NCURSES_LIB)
		@ make fclean -s -C $(SFML_LIB)

re: 
		@ make re -s -C $(NCURSES_LIB)
		@ make re -s -C $(SFML_LIB)

.PHONY: all clean fclean re